@echo off
echo Running Python backend for Pet Verification...
echo Setting up virtual environment if it doesn't exist...
IF NOT EXIST venv (
    python -m venv venv
)
call venv\Scripts\activate.bat
echo Installing requirements...
pip install -r requirements.txt
echo Starting FastAPI application...
uvicorn main:app --host 0.0.0.0 --port 8000 --reload
pause
